currency:
  available:
    - "RUB"
cost:
  rub:
    perKg: 400
    minimal: 350
    perCubicMeter: 10000

dimension:
  weight:
    min: 0
    max: 150000
  length:
    min: 0
    max: 1500
  width:
    min: 0
    max: 1500
  height:
    min: 0
    max: 1500
  stepNormalize: 50
  distanceBaseCost: 450

coordinates-points:
  coordinates:
    departure:
      latitude:
        min: 45
        max: 65
      longitude :
        min: 30
        max: 96
    destination:
      latitude:
        min: 45
        max: 65
      longitude :
        min: 30
        max: 96
